# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 01:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ask_cfpb', '0017_auto_20181217_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpage',
            name='answer_content',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.RichTextBlock())], blank=True),
        ),
    ]
