# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-30 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0006_auto_20190629_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepaid',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prepaid',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
